require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PromoSlotsController do

  # This should return the minimal set of attributes required to create a valid
  # PromoSlot. As you add validations to PromoSlot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PromoSlotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all promo_slots as @promo_slots" do
      promo_slot = PromoSlot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:promo_slots).should eq([promo_slot])
    end
  end

  describe "GET show" do
    it "assigns the requested promo_slot as @promo_slot" do
      promo_slot = PromoSlot.create! valid_attributes
      get :show, {:id => promo_slot.to_param}, valid_session
      assigns(:promo_slot).should eq(promo_slot)
    end
  end

  describe "GET new" do
    it "assigns a new promo_slot as @promo_slot" do
      get :new, {}, valid_session
      assigns(:promo_slot).should be_a_new(PromoSlot)
    end
  end

  describe "GET edit" do
    it "assigns the requested promo_slot as @promo_slot" do
      promo_slot = PromoSlot.create! valid_attributes
      get :edit, {:id => promo_slot.to_param}, valid_session
      assigns(:promo_slot).should eq(promo_slot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PromoSlot" do
        expect {
          post :create, {:promo_slot => valid_attributes}, valid_session
        }.to change(PromoSlot, :count).by(1)
      end

      it "assigns a newly created promo_slot as @promo_slot" do
        post :create, {:promo_slot => valid_attributes}, valid_session
        assigns(:promo_slot).should be_a(PromoSlot)
        assigns(:promo_slot).should be_persisted
      end

      it "redirects to the created promo_slot" do
        post :create, {:promo_slot => valid_attributes}, valid_session
        response.should redirect_to(PromoSlot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved promo_slot as @promo_slot" do
        # Trigger the behavior that occurs when invalid params are submitted
        PromoSlot.any_instance.stub(:save).and_return(false)
        post :create, {:promo_slot => { "product_id" => "invalid value" }}, valid_session
        assigns(:promo_slot).should be_a_new(PromoSlot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PromoSlot.any_instance.stub(:save).and_return(false)
        post :create, {:promo_slot => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested promo_slot" do
        promo_slot = PromoSlot.create! valid_attributes
        # Assuming there are no other promo_slots in the database, this
        # specifies that the PromoSlot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PromoSlot.any_instance.should_receive(:update_attributes).with({ "product_id" => "1" })
        put :update, {:id => promo_slot.to_param, :promo_slot => { "product_id" => "1" }}, valid_session
      end

      it "assigns the requested promo_slot as @promo_slot" do
        promo_slot = PromoSlot.create! valid_attributes
        put :update, {:id => promo_slot.to_param, :promo_slot => valid_attributes}, valid_session
        assigns(:promo_slot).should eq(promo_slot)
      end

      it "redirects to the promo_slot" do
        promo_slot = PromoSlot.create! valid_attributes
        put :update, {:id => promo_slot.to_param, :promo_slot => valid_attributes}, valid_session
        response.should redirect_to(promo_slot)
      end
    end

    describe "with invalid params" do
      it "assigns the promo_slot as @promo_slot" do
        promo_slot = PromoSlot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PromoSlot.any_instance.stub(:save).and_return(false)
        put :update, {:id => promo_slot.to_param, :promo_slot => { "product_id" => "invalid value" }}, valid_session
        assigns(:promo_slot).should eq(promo_slot)
      end

      it "re-renders the 'edit' template" do
        promo_slot = PromoSlot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PromoSlot.any_instance.stub(:save).and_return(false)
        put :update, {:id => promo_slot.to_param, :promo_slot => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested promo_slot" do
      promo_slot = PromoSlot.create! valid_attributes
      expect {
        delete :destroy, {:id => promo_slot.to_param}, valid_session
      }.to change(PromoSlot, :count).by(-1)
    end

    it "redirects to the promo_slots list" do
      promo_slot = PromoSlot.create! valid_attributes
      delete :destroy, {:id => promo_slot.to_param}, valid_session
      response.should redirect_to(promo_slots_url)
    end
  end

end
